# Generated by Django 3.2.7 on 2021-09-15 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='آدرس دسته بندی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuition',
            name='tiotion',
            field=models.IntegerField(verbose_name='شهریه'),
        ),
    ]
