# Generated by Django 3.2.7 on 2021-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0002_auto_20210915_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='شهریه')),
                ('session', models.ManyToManyField(to='gym_register.Tuition', verbose_name='جلسه')),
            ],
            options={
                'verbose_name_plural': 'شهریه',
            },
        ),
    ]
