# Generated by Django 3.2.7 on 2021-09-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0005_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='slug',
        ),
    ]
