# Generated by Django 3.2.7 on 2021-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='natioral_code',
            field=models.IntegerField(default=0, verbose_name='کد ملی'),
        ),
    ]
