# Generated by Django 3.2.7 on 2021-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0009_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
    ]
