# Generated by Django 3.2.7 on 2021-09-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0010_alter_order_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
