# Generated by Django 3.2.7 on 2021-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0011_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(default=0, max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='natioral_code',
            field=models.IntegerField(default=0, max_length=10, verbose_name='کد ملی'),
        ),
    ]
