# Generated by Django 3.2.7 on 2021-09-20 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0015_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2021, 9, 20, 19, 31, 56, 860327, tzinfo=utc), verbose_name='تاریخ تولد'),
        ),
    ]
