# Generated by Django 3.2.7 on 2021-09-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0018_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.CharField(max_length=10, verbose_name='تاریخ تولد'),
        ),
    ]
